### ISSUE TITLE
URL Generated Has Trailing Slash

### ISSUE THREAD

**Issue by robcthegeek** [DalSoft/DalSoft.RestClient#1]
Hey @DalSoft,

Finally got the chance to hack on this and bumped into this problem.

I'm hacking on something that's using the [PushBullet API](https://docs.pushbullet.com/http/) - specifically (to get started) [this resource](https://docs.pushbullet.com/v2/users/me/).

I fired off a request like so:

#### Failing Code

```csharp
dynamic client = CreateClient();
Me result = await client.Users.Me.Get();
return result;
```

This blew up hard, due to Implicit casting failing - but when I checked Fiddler, I noticed that I'd got a 404 back from the server.

#### Failing Request

```
GET https://api.pushbullet.com/v2/users/me/ HTTP/1.1
Authorization: Bearer {token}
Host: api.pushbullet.com
Connection: Keep-Alive
```

#### Failing Response

```
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
Date: Sat, 31 Jan 2015 13:12:35 GMT
Server: Google Frontend
Cache-Control: private
Content-Length: 100

{"error": {"type":"invalid_request","message":"The resource could not be found.","cat":"~(=^‥^)"}}
```

(lulz at the `cat`} :grinning: 

I then hacked the request to **remove the trailing slash** and _all was fine_.

### Successful Request

```
GET https://api.pushbullet.com/v2/users/me HTTP/1.1
Authorization: Bearer {token}
Host: api.pushbullet.com
Connection: Keep-Alive
```

There's still huge debate about whether or not trailing slashes should or shouldn't be there. I personally err on the side of:

> "fuck it, if there isn't one we _definitely_ know what resource they're trying to access."

What do you think? I had a quick look through the code and it seems [this code](https://github.com/DalSoft/DalSoft.RestClient/blob/e782bdcc28db8d60bbffd01cae3ba5c68dae21b7/DalSoft.RestClient/MemberAccessWrapper.cs#L53) is what needs to be looked at?

Happy to open a PR if wanted :smile:

**Comment by robcthegeek** [comment]
PS: At the very least, is there any way I can hack the URL pre-sending? :smile:

**Comment by DalSoft** [comment]
Good point on the slash I think I've had a problem the other way round with http://jsonplaceholder.typicode.com. This makes me think it should be configurable. I did a bit of of a refactor on the core Friday going to pull this in tonight. I'll add this change in too. 

At the moment I've been failing hard on the http method, but considering not doing this to allow checking of the HttpReponseMessage in your case.

As of now this pattern ensures the cast doesn't bork.

```cs
dynamic client = CreateClient();
var result = await client.Users.Me.Get();
If (result.HttpResponseMessage.IsSuccessStatusCode) 
{
    Me me  = result;
}
```

Thanks for spending time looking at it. Want it to be as usable as possible so the more feedback the better!

**Comment by robcthegeek** [comment]
I'm not sure I understand the bit about the cast borking - would never get inside the `if` as the server is 404'ing due to the trailing slash.

**Comment by robcthegeek** [comment]
I'm thinking that rather than add a configuration variable, why not have an optional param to `Get` (and other methods) that allows tweaking of request pre-send? A la:

```csharp
Me result = client.Users.Me.Get(preReq: (request) => request.RequestUri = "https://www.youtube.com/watch?v=QH2-TGUlwu4");
```

This aside probably should have the removal of the trailing slash as standard. This could just be a nice feature to enable people to hack if they need to,

**Comment by DalSoft** [comment]
I've doubled checked and http://jsonplaceholder.typicode.com worked with and without trailing slash - don't know why I thought it wouldn't :) So I can't see a reason not to make removal of the trailing slash the default. The nice thing now that is the default is you can use the Resource method should you require a trailing slash for some reason.
```cs
await client.Users.Me.Get.Resource("/')
```

I've pushed a new version with a load of fixes including this, let me know how you get on.

**Comment by robcthegeek** [comment]
Awesome @DalSoft - thanks!
