### ISSUE TITLE
Work With FormDataCollection 

### ISSUE THREAD

**Issue by MAliM1988** [DalSoft/DalSoft.RestClient#100]
Hi everyone

how can i work with FormDataCollection (for handling multi parameter from body) in DalSoft.RestClient?

**Comment by DalSoft** [comment]
Hey,

RestClient supports "application/x-www-form-urlencoded" using [FormUrlEncodedHandler](https://restclient.dalsoft.io/docs/formurlencodedhandler/) I think this is what you want, you don't need do with FormDataCollection directly RestClient takes care of it for you.

Example:
cs```
var config = new Config() //Build a pipeline using extension methods
                    .UseFormUrlEncodedHandler();

var restClient = new RestClient("http://jsonplaceholder.typicode.com", config);
var user = new User { name="foo", email="foo@bar.com" };

// POST  "application/x-www-form-urlencoded"  name=foo&email=foo@bar.com  http://jsonplaceholder.typicode.com/users/1
var result = await client
      .Headers(new Headers { { "Content-Type", "application/x-www-form-urlencoded" }})
      .Resource("User")
      .Post(user);
```

Does this do what you need, if not let me know and I'll try and help.

**Comment by DalSoft** [comment]
Closing please re-open if your issue isn't resolved.
