### ISSUE TITLE
Autofac integration

### ISSUE THREAD

**Issue by userjeff3** [DalSoft/DalSoft.RestClient#107]
Can IRestClientFactory be registered with Autofac? This would be for backend applications, no ASP, so no controllers, etc.

**Comment by DalSoft** [comment]
IRestClientFactory works with ASP.NET, I don't really use AutoFac but you should be able to set it up as described [here(https://www.thecodebuzz.com/configure-httpclientfactory-autofac-di-httpclient/)] just swap IHttpClientFactory with IHttpRestClientFactory.

**Comment by nhaberl** [comment]
@DalSoft would be of great value to extend your docs with DI setup of different container software like autofac and SimpleInjector ...
So we would have to register IHttpRestClientFactory with HttpClientFactory and how to continue ? (Independent of ASP.NET Core)

**Comment by DalSoft** [comment]
Happy to take PR's for the documentation. But I won't be adding extra DI examples as most people use .NET DI.
