### ISSUE TITLE
custom routes?

### ISSUE THREAD

**Issue by BKSpurgeon** [DalSoft/DalSoft.RestClient#16]
hi all

thank you for your library. i would love to learn more about it.

Is it possible to create custom routes for just one operation:

i.e. i need something like this:

clients/find_by_name/:name

where :name is essentially :id - i'll be using that parameter to search for a client with a matching name - and if i should so find one, then a json object representing that client will be returned.

right now i'll just have to create three different new rest clients with different urls. not sure if that's the way to go though.

rgds

Ben

**Comment by DalSoft** [comment]
Sure it's exactly the scenario I built the Rest Client for.
This example will issue a GET request that looks like http://yourapi/clients/find_by_name/Darran

using (dynamic restApi = new RestClient("http://yourapi"))
{
   var result = await restApi.Clients.Find_By_Name.Get("Darran")
}

**Comment by BKSpurgeon** [comment]
Ok chrs I get it now.  I have the added benefit of not knowing how to use it. So I hope to write some wiki articles especially from noobs viewpoint.
