### ISSUE TITLE
RestClientResponseObject

### ISSUE THREAD

**Issue by nunocorreia85** [DalSoft/DalSoft.RestClient#18]
Hi, 

In RestClientResponseObject.TryGetMember method the order is incorrect:

First should be-> 
if (binder.Name == "HttpResponseMessage") {
     result = _httpResponseMessage;
     return true;
}
Then the rest of the code, because I have a different response message depending on the HttpResponseMessage.StatusCode.

Thanks

**Comment by DalSoft** [comment]
Agreed I'll add it as a  fix in the next release.

Casting to HttpResponseMessage rather than looking at the HttpResponseMessage property will workaround this.

**Comment by DalSoft** [comment]
Also could you post example code that isn't working for your so I can write a test around it
