### ISSUE TITLE
Not sure how to do a query string

### ISSUE THREAD

**Issue by tekadept** [DalSoft/DalSoft.RestClient#37]
I've looked at the query string examples but not sure how to do what I want
I basically need to pass 3 queries from date, todate and api_key which looks like below.
http://apiurl/pay-runs?fromDate=date&toDate=date&api_key=apikey

i tried addint this to where the queries stoart .Query(new { api_key = apikey }).Query(new { fromDate = dfrom }).Query(new { toDate = dto }).get()

but it doesnt seem to work.
what is the correct way for this scenario?

**Comment by DalSoft** [comment]
@tekadept did you get it working?

```cs 
var restClient = new RestClient("http://apiurl");

var response = restClient.Resource("pay-runs").Query(new 
{ 
  fromDate=date,
  toDate=date,
  api_key=apikey 
});

Console.Writeline(response.ToString());
```

> Notice you have to escape  pay-runs using [resource](https://github.com/DalSoft/DalSoft.RestClient/wiki/How-to-Access-Resources) or you could just new up `new RestClient("http://apiurl/pay-runs"); `

**Comment by tekadept** [comment]
Hi, thanks for that. I kind of got it working , but that way works much better. thanks for the help.
