### ISSUE TITLE
Proxy support 

### ISSUE THREAD

**Issue by OptimOSPr1me** [DalSoft/DalSoft.RestClient#46]
Hi, i'm looking for a way to use proxies (http/socks/chains) 
Is that possible ?

**Comment by DalSoft** [comment]
Sure I'll add it to the the documentation, but all you really need to know is that DalSoft.RestClient uses HttpClient under the hood, so you just pass a HttpClientHandler like you would with HttpClient.

```cs
HttpClientHandler httpClientHandler = new HttpClientHandler()
{
    Proxy = new WebProxy("https://myproxy", false),
    PreAuthenticate = true,
    UseDefaultCredentials = false,
    Credentials = new NetworkCredential("MyUserName", "MyPassword");
};

dynamic restClient = new RestClient("https://whatismyipaddress.com", new Config(httpClientHandler));
```

**Comment by DalSoft** [comment]
Closing as provided example appears to work. please reopen if this isn't the case.
