### ISSUE TITLE
"varible": null, returns as member not found (json)

### ISSUE THREAD

**Issue by makkesk8** [DalSoft/DalSoft.RestClient#5]
An exception of type 'System.InvalidOperationException' occurred in DalSoft.RestClient.dll but was not handled in user code

Additional information: Member not found "varible"

**Comment by DalSoft** [comment]
Seen this recently myself, working on it tomorrow night. As a workaroud set it to a default for example 
```json
{
'variable1' : '',
'variable2' : 0
}
```

**Comment by DalSoft** [comment]
Fixed this occurs when a REST API omits null values from the JSON response. My Rest Client now returns null when attempting to access these member dynamically. If this still doesn't work for you, I suggest implicitly casting the result (see readme), and setting the defaults you require.
