### ISSUE TITLE
Update Documentation 

### ISSUE THREAD

**Issue by DalSoft** [DalSoft/DalSoft.RestClient#72]

**Comment by AKrasheninnikov** [comment]
I'd like to help a bit if you explain the scope.

**Comment by DalSoft** [comment]
Thanks that would really help, I'll commit a RC branch of 3.3.3 tonight so you can see what has changed in the RestClient. I need to add / change user documentation for these stories: 

https://github.com/DalSoft/DalSoft.RestClient/issues/70
https://github.com/DalSoft/DalSoft.RestClient/issues/73
https://github.com/DalSoft/DalSoft.RestClient/issues/45
https://github.com/DalSoft/DalSoft.RestClient/issues/64
https://github.com/DalSoft/DalSoft.RestClient/issues/56

I've just added you as a collaborator for DalSoft.RestClient.Pages

**Comment by AKrasheninnikov** [comment]
Hi Darran, I can only see the **master** branch so far. Postponed a bit?

**Comment by DalSoft** [comment]
Sorry yes, I'll try and resume work on this this week.

**Comment by AKrasheninnikov** [comment]
Please update me when you start working. I need to plan time for this if you still need help.

**Comment by DalSoft** [comment]
Got time to finish Version 4.0, added a quick blog write up of the features 

https://www.dalsoft.co.uk/blog/index.php/2019/08/04/csharp-rest-client-now-with-static-typing/

@AKrasheninnikov if you still wanted to help writing up the official documentation that would be greatly appreciated.
