### ISSUE TITLE
How Can I Redirect with DalSoft.RestClient

### ISSUE THREAD

**Issue by MAliM1988** [DalSoft/DalSoft.RestClient#78]
Hello everyone 

How can i redirect with DalSoft.RestClient on 302 http Code?

Thanks

**Comment by DalSoft** [comment]
Sorry I need little bit more information about what your trying to do, perhaps a code example? If it's a server side redirect it should work as your would expect and follow the redirect.

**Comment by MAliM1988** [comment]
Hi Thanks for your Answer

my Question on base is wrong sorry
