### ISSUE TITLE
Question:  Is a way to omit fields at runtime?

### ISSUE THREAD

**Issue by wa1gon** [DalSoft/DalSoft.RestClient#79]
I am calling POSTsand PUTs to CouchDB.  

There are two required fields for PUT _id and _rev, however, that must not be in the POST method.  Is there a way to exclude them from the POST?

Thank you very much for making this library available.

**Comment by DalSoft** [comment]
The easiest way to do this is is use JSON.NET [Conditional Property Serialization](https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm),  you could also use a [Delegating Handler](https://restclient.dalsoft.io/docs/using-delegatinghandlers/).

I updated the repo [DalSoft.RestClient.Examples.CouchDb](https://github.com/DalSoft/DalSoft.RestClient.Examples.CouchDb)  to include a test showing Conditional Property Serialization.

Let me know if this works for you.

**Comment by DalSoft** [comment]
Closing as answered please reopen if this is still an issue.
