### ISSUE TITLE
Add ability to send delete body

### ISSUE THREAD

**Issue by yairsherf** [DalSoft/DalSoft.RestClient#95]
Delete request should have ability to send body
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/delete

**Comment by DalSoft** [comment]
This is something on the [todo list,](https://github.com/DalSoft/DalSoft.RestClient/issues/67) is it blocking you at the moment? If it is I'll prioritize it for [next release.](https://github.com/DalSoft/DalSoft.RestClient/projects/4)

**Comment by yairsherf** [comment]
Hi
Yes its very important for me and blocking my work with the cloud.
Can you tell me when is the next release?
Thanks a lot

**Comment by DalSoft** [comment]
Released 4.2.0
